-- Found ament_cmake: 0.9.9 (/home/ros-vm/ros2_foxy/ros2-linux/share/ament_cmake/cmake)
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Found ament_lint_auto: 0.9.6 (/home/ros-vm/ros2_foxy/ros2-linux/share/ament_lint_auto/cmake)
-- Found rosidl_default_generators: 1.0.1 (/home/ros-vm/ros2_foxy/ros2-linux/share/rosidl_default_generators/cmake)
-- Using all available rosidl_typesupport_c: rosidl_typesupport_connext_c;rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
-- Found rosidl_adapter: 1.2.1 (/home/ros-vm/ros2_foxy/ros2-linux/share/rosidl_adapter/cmake)
-- Could not find RTI Connext - skipping rosidl_typesupport_connext_c
-- Could not find RTI Connext - skipping rosidl_typesupport_connext_cpp
-- Using all available rosidl_typesupport_cpp: rosidl_typesupport_connext_cpp;rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
-- Found geometry_msgs: 2.0.5 (/home/ros-vm/ros2_foxy/ros2-linux/share/geometry_msgs/cmake)
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
CMake Error at /home/ros-vm/ros2_foxy/ros2-linux/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:60 (message):
  execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
  rover_utils --arguments-file
  /home/ros-vm/github/auton_sys-23/utils/build/rover_utils/rosidl_adapter__arguments__rover_utils.json
  --output-dir
  /home/ros-vm/github/auton_sys-23/utils/build/rover_utils/rosidl_adapter/rover_utils
  --output-file
  /home/ros-vm/github/auton_sys-23/utils/build/rover_utils/rosidl_adapter/rover_utils.idls)
  returned error code 1:

  Traceback (most recent call last):

    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/home/ros-vm/ros2_foxy/ros2-linux/lib/python3.8/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/home/ros-vm/ros2_foxy/ros2-linux/lib/python3.8/site-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/home/ros-vm/ros2_foxy/ros2-linux/lib/python3.8/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
    File "/home/ros-vm/ros2_foxy/ros2-linux/lib/python3.8/site-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
      msg = parse_message_string(package_name, input_file.stem, content)
    File "/home/ros-vm/ros2_foxy/ros2-linux/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 540, in parse_message_string
      msg = MessageSpecification(pkg_name, msg_name, fields, constants)
    File "/home/ros-vm/ros2_foxy/ros2-linux/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 387, in __init__
      self.base_type = BaseType(
    File "/home/ros-vm/ros2_foxy/ros2-linux/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 204, in __init__
      raise InvalidResourceName(

  rosidl_adapter.parser.InvalidResourceName: 'tank_drive' is an invalid
  message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'

Call Stack (most recent call first):
  /home/ros-vm/ros2_foxy/ros2-linux/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:38 (rosidl_generate_interfaces)


-- Configuring incomplete, errors occurred!
See also "/home/ros-vm/github/auton_sys-23/utils/build/rover_utils/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:988: cmake_check_build_system] Error 1
